<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>UniversalBFF.AspHost</AssemblyName>
    <RootNamespace>UniversalBFF</RootNamespace>
    <Deterministic>false</Deterministic>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ImportedNamespaces></ImportedNamespaces>
  </PropertyGroup>

  <!-- META DATA -->

  <PropertyGroup>
    <PackageId>UniversalBFF.AspHost</PackageId>
    <Description>UniversalBFF.AspHost</Description>
    <Product>UniversalBFF</Product>
    <PackageTags></PackageTags>
    <Company></Company>
    <Copyright></Copyright>
    <Authors></Authors>
    <!-- VERSION -->
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1</AssemblyVersion>
    <FileVersion>1.0.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- ADDITIONAL ASSEMBLY-ATTRIBUTES -->
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>SourceContext</_Parameter1>
      <_Parameter2>UniversalBFF.AspHost</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

  <!-- BUILD -->

  <PropertyGroup>
    <OutputPath>..\..\dist</OutputPath>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <DefineConstants>$(DefineConstants);NET_CORE;NET_8_;NET_10_;NET_10</DefineConstants>
    <NoWarn>$(NoWarn);1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);TRACE;DEBUG</DefineConstants>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <Target Name="_ResolveCopyLocalNuGetPkgXmls" AfterTargets="ResolveReferences">
    <ItemGroup>
      <!-- Copy also XML-Doc files from all PackageReferences to output dir -->
      <ReferenceCopyLocalPaths Include="@(ReferenceCopyLocalPaths->'%(RootDir)%(Directory)%(Filename).xml')" Condition="'%(ReferenceCopyLocalPaths.NuGetPackageId)'!='' and Exists('%(RootDir)%(Directory)%(Filename).xml')" />
    </ItemGroup>
  </Target>

  <!-- REFERENCES -->

  <ItemGroup>

    <!-- any additional MS-near references to get complete access to asp, is provided by this dependency-package: -->
    <PackageReference Include="SmartStandards.WebApiDependencies.net10.0" Version="10.0.12" />

    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />

    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />

    <PackageReference Include="UJMW.DynamicClient" Version="5.6.2" />
    <PackageReference Include="UJMW.DynamicController" Version="5.6.2" />

    <PackageReference Include="SmartStandards.AuthTokenHandling" Version="5.1.1" />
    <PackageReference Include="SmartStandards.AuthTokenHandling.MvcSupport" Version="5.1.1" />

    <PackageReference Include="SmartAmbience" Version="2.5.1" />
    <PackageReference Include="SmartAmbience.MvcSupport" Version="2.5.1" />

    <PackageReference Include="SmartStandards.Essentials" Version="1.0.1" />

    <PackageReference Include="SmartStandards.Logging" Version="3.4.4" />
    <PackageReference Include="SmartStandards.Logging.AspSupport" Version="3.4.4" />

    <PackageReference Include="Snowflake44" Version="3.8.3" />

    <PackageReference Include="UShell.FrontendBundle" Version="3.2.32.1494" />
    <PackageReference Include="UShell.FrontendBundle.Mvc" Version="3.2.32.1494" />
    <PackageReference Include="UShell.PortfolioDescription" Version="4.1.2" />
    <PackageReference Include="UShell.PortfolioHosting.Mvc" Version="4.1.2" />
    <PackageReference Include="UShell.ServerCommands.Contract" Version="1.2.1" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UniversalBFF.ModuleContract.net10.0\UniversalBFF.ModuleContract.net10.0.csproj" />
    <ProjectReference Include="..\UniversalBFF.net10.0\UniversalBFF.net10.0.csproj" />
  </ItemGroup>

  <!-- INCLUDEs and FILEs -->

  <Import Project="..\UniversalBFF.AspNetCore\UniversalBFF.AspNetCore.projitems" Label="Shared" />

  <ItemGroup>
    <Compile Remove="Logs\**" />
    <Compile Remove="Util\**" />
    <Content Remove="Logs\**" />
    <Content Remove="Util\**" />
    <EmbeddedResource Remove="Logs\**" />
    <EmbeddedResource Remove="Util\**" />
    <None Remove="Logs\**" />
    <None Remove="Util\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="_AnnouncementInfo.txt" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>