<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>UniversalBFF.WebViewHost</AssemblyName>
    <RootNamespace>UniversalBFF</RootNamespace>
    <Deterministic>false</Deterministic>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ImportedNamespaces></ImportedNamespaces>
    <OutputType>WinExe</OutputType>
    <Platforms>x64;x86</Platforms>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <!-- META DATA -->

  <PropertyGroup>
    <PackageId>UniversalBFF.WebViewHost</PackageId>
    <Description>UniversalBFF.WebViewHost</Description>
    <Product>UniversalBFF.WebViewHost</Product>
    <PackageTags></PackageTags>
    <Company>SmartStandards</Company>
    <Copyright>SmartStandards</Copyright>
    <Authors>SmartStandards</Authors>
    <!-- VERSION -->
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1</AssemblyVersion>
    <FileVersion>1.0.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- ADDITIONAL ASSEMBLY-ATTRIBUTES -->
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>SourceContext</_Parameter1>
      <_Parameter2>UniversalBFF.WebViewHost</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

  <!-- BUILD -->

  <PropertyGroup>
    <OutputPath>..\..\dist</OutputPath>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <DefineConstants>$(DefineConstants);NET_CORE;NET_8_;NET_10_;NET_10</DefineConstants>
    <NoWarn>$(NoWarn);1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DefineConstants>$(DefineConstants);TRACE;DEBUG</DefineConstants>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <DefineConstants>$(DefineConstants);TRACE;DEBUG</DefineConstants>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <Target Name="_ResolveCopyLocalNuGetPkgXmls" AfterTargets="ResolveReferences">
    <ItemGroup>
      <!-- Copy also XML-Doc files from all PackageReferences to output dir -->
      <ReferenceCopyLocalPaths Include="@(ReferenceCopyLocalPaths->'%(RootDir)%(Directory)%(Filename).xml')" Condition="'%(ReferenceCopyLocalPaths.NuGetPackageId)'!='' and Exists('%(RootDir)%(Directory)%(Filename).xml')" />
    </ItemGroup>
  </Target>

  <!-- REFERENCES -->

  <ItemGroup>

    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <!-- any additional MS-near references to get complete access to asp, is provided by this dependency-package: -->
    <PackageReference Include="SmartStandards.WebApiDependencies.net10.0" Version="10.0.15" />

    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SmartStandards.Logging" Version="3.4.4" />
    <PackageReference Include="UJMW.DynamicClient" Version="5.6.2" />

    <!-- THIS APP CONTAINS AN SEAMLESS BROWSER CONTROL WITHIN ITS UI -->
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="8.0.0" />

    <PackageReference Include="UJMW.DynamicController" Version="5.6.2" />
    <PackageReference Include="SmartStandards.AuthTokenHandling.MvcSupport" Version="5.1.1" />
    <PackageReference Include="SmartStandards.Logging.AspSupport" Version="3.4.4" />

    <PackageReference Include="SmartAmbience" Version="3.2.1" />
    <PackageReference Include="SmartAmbience.MvcSupport" Version="3.2.1" />

    <PackageReference Include="UShell.FrontendBundle" Version="3.2.32.1494" />
    <PackageReference Include="UShell.FrontendBundle.Mvc" Version="3.2.32.1494" />
    <PackageReference Include="UShell.PortfolioDescription" Version="4.1.3" />
    <PackageReference Include="UShell.PortfolioHosting.Mvc" Version="4.1.3" />
    <PackageReference Include="UShell.ServerCommands.Contract" Version="1.2.1" />

    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />

    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.0" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UniversalBFF.ModuleContract.net10.0\UniversalBFF.ModuleContract.net10.0.csproj" />
    <ProjectReference Include="..\UniversalBFF.net10.0\UniversalBFF.net10.0.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <!-- INCLUDEs and FILEs -->

  <Import Project="..\UniversalBFF.AspNetCore\UniversalBFF.AspNetCore.projitems" Label="Shared" />

  <ItemGroup>
    <Compile Remove="BrowserForm.cs" />
    <Compile Remove="BrowserForm.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="BrowserForm.resx" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="window_earth.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="AppIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="WebViewAspNetCoreAdapter.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WebViewAspNetCoreAdapter.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="WebViewAspNetCoreAdapter.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>WebViewAspNetCoreAdapter.cs</LastGenOutput>
      <CustomToolNamespace>UniversalBFF</CustomToolNamespace>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="[MyProject]\" />
  </ItemGroup>

</Project>